# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/marcelo/Desktop/APRESENTACAO_VESPA/Comecar_com_perifericos/vsp/vsp.srcs/sources_1/bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_IP_Instruction_31_24_2/Instruction_Mem_IP_IP_Instruction_31_24_2.xci
# IP: The module: 'Instruction_Mem_IP_IP_Instruction_31_24_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/marcelo/Desktop/APRESENTACAO_VESPA/Comecar_com_perifericos/vsp/vsp.gen/sources_1/bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_IP_Instruction_31_24_2/Instruction_Mem_IP_IP_Instruction_31_24_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instruction_Mem_IP_IP_Instruction_31_24_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/marcelo/Desktop/APRESENTACAO_VESPA/Comecar_com_perifericos/vsp/vsp.srcs/sources_1/bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_IP_Instruction_31_24_2/Instruction_Mem_IP_IP_Instruction_31_24_2.xci
# IP: The module: 'Instruction_Mem_IP_IP_Instruction_31_24_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/marcelo/Desktop/APRESENTACAO_VESPA/Comecar_com_perifericos/vsp/vsp.gen/sources_1/bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_IP_Instruction_31_24_2/Instruction_Mem_IP_IP_Instruction_31_24_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instruction_Mem_IP_IP_Instruction_31_24_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
