# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Teste_Opcode.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Conct_Out_RAM_0_1/design_1_Conct_Out_RAM_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Conct_Out_RAM_0_1 || ORIG_REF_NAME==design_1_Conct_Out_RAM_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAM_IP_31_24_0/design_1_RAM_IP_31_24_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_RAM_IP_31_24_0 || ORIG_REF_NAME==design_1_RAM_IP_31_24_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAM_IP_31_24_1/design_1_RAM_IP_31_24_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_RAM_IP_31_24_1 || ORIG_REF_NAME==design_1_RAM_IP_31_24_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAM_IP_31_24_2/design_1_RAM_IP_31_24_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_RAM_IP_31_24_2 || ORIG_REF_NAME==design_1_RAM_IP_31_24_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0_1/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SliptD_IN_RAM_0_1/design_1_SliptD_IN_RAM_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_SliptD_IN_RAM_0_1 || ORIG_REF_NAME==design_1_SliptD_IN_RAM_0_1} -quiet] -quiet

# Block Designs: bd/RegFile_IP/RegFile_IP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFile_IP || ORIG_REF_NAME==RegFile_IP} -quiet] -quiet

# IP: bd/RegFile_IP/ip/RegFile_IP_blk_mem_gen_0_0/RegFile_IP_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFile_IP_blk_mem_gen_0_0 || ORIG_REF_NAME==RegFile_IP_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/RegFile_IP/ip/RegFile_IP_blk_mem_gen_0_1/RegFile_IP_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFile_IP_blk_mem_gen_0_1 || ORIG_REF_NAME==RegFile_IP_blk_mem_gen_0_1} -quiet] -quiet

# Block Designs: bd/Instruction_Mem_IP/Instruction_Mem_IP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP || ORIG_REF_NAME==Instruction_Mem_IP} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_blk_mem_gen_0_0/Instruction_Mem_IP_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_blk_mem_gen_0_0 || ORIG_REF_NAME==Instruction_Mem_IP_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_IP_Instruction_31_24_0/Instruction_Mem_IP_IP_Instruction_31_24_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_IP_Instruction_31_24_0 || ORIG_REF_NAME==Instruction_Mem_IP_IP_Instruction_31_24_0} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_IP_Instruction_31_24_1/Instruction_Mem_IP_IP_Instruction_31_24_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_IP_Instruction_31_24_1 || ORIG_REF_NAME==Instruction_Mem_IP_IP_Instruction_31_24_1} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_IP_Instruction_31_24_2/Instruction_Mem_IP_IP_Instruction_31_24_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_IP_Instruction_31_24_2 || ORIG_REF_NAME==Instruction_Mem_IP_IP_Instruction_31_24_2} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_Address_Adder_0_1/Instruction_Mem_IP_Address_Adder_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_Address_Adder_0_1 || ORIG_REF_NAME==Instruction_Mem_IP_Address_Adder_0_1} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_Address_Adder_0_2/Instruction_Mem_IP_Address_Adder_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_Address_Adder_0_2 || ORIG_REF_NAME==Instruction_Mem_IP_Address_Adder_0_2} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_Address_Adder_1_0/Instruction_Mem_IP_Address_Adder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_Address_Adder_1_0 || ORIG_REF_NAME==Instruction_Mem_IP_Address_Adder_1_0} -quiet] -quiet

# IP: bd/Instruction_Mem_IP/ip/Instruction_Mem_IP_Conct_Out_RAM_0_0/Instruction_Mem_IP_Conct_Out_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instruction_Mem_IP_Conct_Out_RAM_0_0 || ORIG_REF_NAME==Instruction_Mem_IP_Conct_Out_RAM_0_0} -quiet] -quiet

# XDC: /home/marcelo/Desktop/APRESENTACAO_VESPA/Comecar_com_perifericos/vsp/vsp.gen/sources_1/bd/design_1/design_1_ooc.xdc

# XDC: /home/marcelo/Desktop/APRESENTACAO_VESPA/Comecar_com_perifericos/vsp/vsp.gen/sources_1/bd/RegFile_IP/RegFile_IP_ooc.xdc

# XDC: /home/marcelo/Desktop/APRESENTACAO_VESPA/Comecar_com_perifericos/vsp/vsp.gen/sources_1/bd/Instruction_Mem_IP/Instruction_Mem_IP_ooc.xdc
